### ISSUE TITLE
Bug: Player joins and disconnects on `play` command

### ISSUE THREAD

**Issue by hirusha-adi** [cloudwithax/pomice#68]
Pomice version: `2.9.0`
Lavalink version: [`4.0.5`](https://github.com/lavalink-devs/Lavalink/releases/tag/4.0.5)
Discord.py version: `2.2.2`
My Lavalink config: [click here](https://github.com/hirusha-adi/Near/blob/main/lavalink.yml)
Bot's code: [click here](https://github.com/cloudwithax/pomice/blob/main/examples/advanced.py) - i just loaded the advanced-example cog.

Issue: 
(Bot's prefix is `--`), when i run `--play <song-name>`, the bot joins the voice channel that im currently joined it, send a simple embed with the title: `Now playing` followed by the song name and who requested it, and leaves the voice channel. Cannot hear anything even in that 2-5 seconds in which the bot stays joined to the voice channel.

Logs:
After starting up lavalink, and when i try to run: `--play unwritten`, i got this error:
```
2024-05-18T09:54:18.205+05:30  INFO 16636 --- [  XNIO-1 task-2] lavalink.server.io.SocketServer          : Connection successfully established from Pomice/2.9.0
2024-05-18T09:54:32.989+05:30  INFO 16636 --- [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:unwritten"
2024-05-18T09:54:33.754+05:30  INFO 16636 --- [  XNIO-1 task-2] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: unwritten
2024-05-18T09:54:33.800+05:30  INFO 16636 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : GET /v4/loadtracks?identifier=ytsearch:unwritten
2024-05-18T09:54:33.810+05:30  INFO 16636 --- [back-1-thread-1] c.s.d.l.s.y.YoutubeAccessTokenTracker    : Updating YouTube access token (current is null).
2024-05-18T09:54:33.825+05:30  INFO 16636 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/vomd660k1whaznlj/players/1073075414618095617?noReplace=False, payload={"encodedTrack": "QAAA9QMAUE5hdGFzaGEgQmVkaW5nZmllbGQgLSBVbndyaXR0ZW4gKE9mZmljaWFsIFZpZGVvKSAoYXMgZmVhdHVyZWQgaW4gQW55b25lIEJ1dCBZb3UpABNOYXRhc2hhIEJlZGluZ2ZpZWxkAAAAAAADctAAC2I3azBhNWhZblNJAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9YjdrMGE1aFluU0kBADRodHRwczovL2kueXRpbWcuY29tL3ZpL2I3azBhNWhZblNJL21heHJlc2RlZmF1bHQuanBnAAAHeW91dHViZQAAAAAAAAAA", "position": "0", "endTime": null}
2024-05-18T09:54:34.076+05:30  INFO 16636 --- [  XNIO-1 task-3] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/vomd660k1whaznlj/players/1073075414618095617, payload={"voice": {"token": "9f316c31e4ba88f0", "endpoint": "india10000.discord.media:443", "sessionId": "4e2eed4652852b71729f94a481372bff"}}
2024-05-18T09:54:36.171+05:30 ERROR 16636 --- [back-1-thread-1] c.s.d.l.s.y.YoutubeAccessTokenTracker    : YouTube access token update failed.

java.io.IOException: Invalid status code for access token tv response: 400
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.assertSuccessWithContent(HttpClientTools.java:154) ~[lavaplayer-2.1.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.requestAccessToken(YoutubeAccessTokenTracker.java:291) ~[lavaplayer-2.1.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.fetchAccessToken(YoutubeAccessTokenTracker.java:224) ~[lavaplayer-2.1.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.updateAccessToken(YoutubeAccessTokenTracker.java:139) ~[lavaplayer-2.1.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.getAccessToken(YoutubeAccessTokenTracker.java:191) ~[lavaplayer-2.1.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeHttpContextFilter.onRequest(YoutubeHttpContextFilter.java:75) ~[lavaplayer-2.1.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.http.SettableHttpRequestFilter.onRequest(SettableHttpRequestFilter.java:41) ~[lavaplayer-2.1.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpInterface.execute(HttpInterface.java:70) ~[lavaplayer-2.1.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.fetchScript(DefaultYoutubeTrackDetailsLoader.java:282) ~[lavaplayer-2.1.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackInfoFromInnertube(DefaultYoutubeTrackDetailsLoader.java:202) ~[lavaplayer-2.1.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:48) ~[lavaplayer-2.1.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:36) ~[lavaplayer-2.1.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:83) ~[lavaplayer-2.1.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:44) ~[lavaplayer-2.1.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[lavaplayer-2.1.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:330) ~[lavaplayer-2.1.2.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:1589) ~[na:na]

2024-05-18T09:54:42.728+05:30  INFO 16636 --- [back-1-thread-1] c.s.d.l.s.y.YoutubeAccessTokenTracker    : Updating YouTube visitor id (current is null).
2024-05-18T09:54:43.027+05:30  INFO 16636 --- [back-1-thread-1] c.s.d.l.s.y.YoutubeAccessTokenTracker    : Updating YouTube visitor id succeeded, new one is CgtwQVlQNFQtSV9SVSiI26CyBjIKCgJMSxIEGgAgSToMCAEgm9ifu4Gxi6Rm, next update will be after 600 seconds.
2024-05-18T09:54:43.691+05:30  INFO 16636 --- [  XNIO-1 task-3] l.server.io.RequestLoggingFilter         : DELETE /v4/sessions/vomd660k1whaznlj/players/1073075414618095617
```

I waited of couple of minutes and tried again, without closing the bot nor lavalink, and then i got this error:
```
2024-05-18T10:00:09.478+05:30  INFO 16636 --- [  XNIO-1 task-3] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:unwritten"
2024-05-18T10:00:10.318+05:30  INFO 16636 --- [  XNIO-1 task-3] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: unwritten
2024-05-18T10:00:10.321+05:30  INFO 16636 --- [  XNIO-1 task-3] l.server.io.RequestLoggingFilter         : GET /v4/loadtracks?identifier=ytsearch:unwritten
2024-05-18T10:00:10.324+05:30  INFO 16636 --- [  XNIO-1 task-3] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/vomd660k1whaznlj/players/1073075414618095617?noReplace=False, payload={"encodedTrack": "QAAA9QMAUE5hdGFzaGEgQmVkaW5nZmllbGQgLSBVbndyaXR0ZW4gKE9mZmljaWFsIFZpZGVvKSAoYXMgZmVhdHVyZWQgaW4gQW55b25lIEJ1dCBZb3UpABNOYXRhc2hhIEJlZGluZ2ZpZWxkAAAAAAADctAAC2I3azBhNWhZblNJAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9YjdrMGE1aFluU0kBADRodHRwczovL2kueXRpbWcuY29tL3ZpL2I3azBhNWhZblNJL21heHJlc2RlZmF1bHQuanBnAAAHeW91dHViZQAAAAAAAAAA", "position": "0", "endTime": null}
2024-05-18T10:00:10.439+05:30  INFO 16636 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/vomd660k1whaznlj/players/1073075414618095617, payload={"voice": {"token": "2c8a3098b81a9e95", "endpoint": "india10000.discord.media:443", "sessionId": "4e2eed4652852b71729f94a481372bff"}}
2024-05-18T10:00:10.711+05:30  INFO 16636 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : DELETE /v4/sessions/vomd660k1whaznlj/players/1073075414618095617
``` 

still the same behaviour.

**Comment by cloudwithax** [comment]
This is a lavalink error, nothing to do with the library. Please make sure you are keeping your Lavalink instance up to date to prevent any future errors like this.

**Comment by ZandercraftGames** [comment]
Hey @hirusha-adi. So I've looked into this and it seems that this is a result of using the newest version of Lavalink which deprecates the built-in YouTube source since they've moved it to it's own separate plugin as was mentioned in 4.0.5's release notes (https://github.com/lavalink-devs/Lavalink/releases/tag/4.0.5).

If you configure the [YouTube source plugin](https://github.com/lavalink-devs/youtube-source#plugin) with it's default configuration, everything should work. This probably is because Lavalink is sending some form of unrecognized HTTP status code or something to indicate the deprecation that isn't agreeing with the library.
